const  main = document.querySelector('main');
const sectionHero= document.querySelector('.section-hero');

const containerHeader = document.querySelector('header');
const buttonRegister= document.getElementById('button-registrarce')
const buttonLogin = document.querySelector('.button-login')

// informacion de  un producto
const titulo = document.getElementsByTagName('title')[0]

// filtrar
const campo_filtrar = document.querySelector("[input-buscar]")
const lupaIcon=document.querySelector(".buscador-lupa")

// Formulario de contacto 

const buttonsend = document.querySelector('.input-button');
const input_name = document.querySelector('.input-name');
const input_mensaje = document.querySelector('#mensaje')
const sectionContact= document.querySelector('.section-contact')

const contenedorBuscar=document.querySelector('.contenedor-buscador')


