const  main = document.querySelector('main');
const header= document.querySelector('header');

const containerHeader = document.querySelector('header');
const buttonRegister= document.getElementById('button-registrarce')
const buttonLogin = document.querySelector('.button-login')

// informacion de  un producto
const titulo = document.getElementsByTagName('title')[0]

// filtrar
const campo_filtrar = document.querySelector("[input-buscar]")


const contenedorBuscar=document.querySelector('.contenedor-buscador')


