const  main = document.querySelector('main');
const sectionHero= document.querySelector('.section-hero');

const containerHeader = document.querySelector('header');
const sectionProducts= document.getElementsByClassName('section-products')[0]
const buttonRegister= document.getElementById('button-registrarce')

// informacion de  un producto
const titulo = document.getElementsByTagName('title')[0]

// filtrar
const campo_filtrar = document.querySelector("[input-buscar]")
const lupaIcon=document.querySelector(".buscador-lupa")

// Formulario de contacto 

const buttonEnd = document.querySelector('.input-button');
const input_name = document.querySelector('.input-name');
const input_mensaje = document.querySelector('#mensaje')
